---
- hosts: AppServer
  become: yes
  tasks: 
  - name: Installs nginx web server
    Apt: 'name: nginx state: started update_cache: true'
    notify:
    - start nginx
  handlers:
  - name: start nginx
    service:
      name: nginx
      state: started
