version: "3.8"

services:
  postgres:
    container_name: ${CONTAINER_NAME}
    image: postgres:13
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - ${CONTAINER_PORT}:5432
    restart: always
volumes:
  db_data: {}

